### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#27]
I get this error with 1.18

Uncaught TypeError: JTLPluginPaymentMethod::__construct(): Argument #1 ($moduleID) must be of type string, null given, called in /www/htdocs/w00e35d5/plugins/jtl_postfinancecheckout/Bootstrap.php on line 154 and defined in /www/htdocs/w00e35d5/includes/src/Plugin/Payment/Method.php:97
Stack trace:
#0 /www/htdocs/w00e35d5/plugins/jtl_postfinancecheckout/Bootstrap.php(154): JTLPluginPaymentMethod->__construct(NULL)
#1 /www/htdocs/w00e35d5/includes/src/Events/Dispatcher.php(82): Pluginjtl_postfinancecheckoutBootstrap->Pluginjtl_postfinancecheckout{closure}(Array)
#2 /www/htdocs/w00e35d5/includes/src/Plugin/HookManager.php(108): JTLEventsDispatcher->fire(shop.hook.159, Array)
#3 /www/htdocs/w00e35d5/includes/defines.php(318): JTLPluginHookManager->executeHook(159, Array)
#4 /www/htdocs/w00e35d5/includes/src/dbeS/Sync/Orders.php(787): executeHook(159, Array)
#5 /www/htdocs/w00e35d5/includes/src/dbeS/Sync/Orders.php(48): JTLdbeSSyncOrders->handleSet(Array)
#6 /www/htdocs/w00e35d5/includes/src/dbeS/Starter.php(323): JTLdbeSSyncOrders->handle(Object(JTLdbeSStarter))
#7 /www/htdocs/w00e35d5/dbeS/index.php(107): JTLdbeSStarter->start(Bestellungen_xm..., Array, Array)
#8 {main}

And we cant sync the shop with the wawi at the moment.

**Comment by PAO1908CH** [comment]
Tested it again, sync with wawi is not possible anymore, always error 500 and the error log above is created as soon as we try to sync the wawi with the shop.

**Comment by edgaraswallee** [comment]
Hello, @PAO1908CH it should be fixed in 1.0.20

**Comment by PAO1908CH** [comment]
Seems to be solved, thank you.

edgaraswallee ***@***.***> schrieb am Mi., 17. Jan. 2024,
13:58:
